version: "3.7"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "amogh555kashyap"
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"